spring: 
  data: 
    mongodb:
      uri: mongodb://localhost:27017/product_db

eureka:
    client:
        fetch-register: true
        register-with-eureka: true
        defaultZone: http://localhost:8761/eureka
        healcheck:
          enabled: true
    instance:
        preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS