spring:
    application:
        name: eureka
    cloud:
        loadbalancer:
            ribbon:
                enabled: false

eureka:
    client:
        fetch-register: false
        register-with-eureka: false

server:
    port: 8761
