spring:
    application:
        name: eureka

eureka:
    client:
        fetch-register: false
        register-with-eureka: false
    instance: 
        hostname: localhost

server:
    port: 8761
