spring:
    application:
        name: function
    zipkin:
        baseUrl: http://localhost:9411/
        

eureka:
    client:
        fetch-register: true
        register-with-eureka: true
        defaultZone: http://localhost:8761/eureka
    instance:
        preferIpAddress: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    circuitbreakers:
      enabled: true
    health:
      show-details: ALWAYS   

server:
    port: 8020
