spring:
    application:
        name: gateway
    cloud:
        loadbalancer:
            ribbon:
                enabled: false
        gateway:
#            discovery:
 #               locator:
  #                  enabled: true
   #                 lower-case-service-id: true
            routes:
                - id: product-route
                  uri: lb://PRODUCT/
                  predicates:
                    - Path=/product/**
                  filters:
                    - name: CircuitBreaker
                      args:
                        name: product
                        registerHealthIndicator: true
                        failureRateThreshold: 50
                        slidingWindowSize: 20
                        minimumNumberOfCalls: 20
                        waitDurationInOpenState: 10s
                        permmitedNumberOfCallsInHalfOpenState: 5
                - id: review-route
                  uri: lb://REVIEW/
                  predicates: 
                    - Path=/review/**
                  filters:
                    - name: CircuitBreaker
                      args:
                        name: review
                        registerHealthIndicator: true
                        failureRateThreshold: 50
                        slidingWindowSize: 20
                        minimumNumberOfCalls: 20
                        waitDurationInOpenState: 10s
                        permmitedNumberOfCallsInHalfOpenState: 5
                - id: sales-route
                  uri: lb://SALES/
                  predicates: 
                    - Path=/order/**
                  filters:
                      - name: Retry
                        args:
                            retries: 10
                            statuses: BAD_GATEWAY
                            methods: GET
                            backoff:
                                firstBackoff: 10ms
                                maxBackoff: 100ms
                                factor: 2
                                basedOnPreviousValue: false
                      - name: CircuitBreaker
                          args:
                            name: sales
                            registerHealthIndicator: true
                            failureRateThreshold: 50
                            slidingWindowSize: 20
                            minimumNumberOfCalls: 20
                            waitDurationInOpenState: 10s
                            permmitedNumberOfCallsInHalfOpenState: 5
                                

eureka:
    client:
        fetch-register: true
        register-with-eureka: true
        defaultZone: http://localhost:8761/eureka
    instance:
        preferIpAddress: true
        lease-expiration-duration-in-seconds: 10
    
server:
    port: 8090
    
management:
  endpoint:
    gateway:
      enabled: true
    circuitbreakers:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
