spring:
    application:
        name: gateway
    cloud:
        loadbalancer:
            ribbon:
                enabled: false
        gateway:
#            discovery:
 #               locator:
  #                  enabled: true
   #                 lower-case-service-id: true
            routes:
                - id: product-route
                  uri: lb://PRODUCT/
                  predicates:
                    - Path=/product/**
                  filters:
                      - name: Retry
                        args:
                            retries: 10
                            statuses: BAD_GATEWAY
                            methods: GET
                            backoff:
                                firstBackoff: 10ms
                                maxBackoff: 100ms
                                factor: 2
                                basedOnPreviousValue: false
                - id: review-route
                  uri: lb://REVIEW/
                  predicates: 
                    - Path=/review/**
                  filters:
                      - name: Retry
                        args:
                            retries: 10
                            statuses: BAD_GATEWAY
                            methods: GET
                            backoff:
                                firstBackoff: 10ms
                                maxBackoff: 100ms
                                factor: 2
                                basedOnPreviousValue: false
                - id: sales-route
                  uri: lb://SALES/
                  predicates: 
                    - Path=/order/**
                  filters:
                      - name: Retry
                        args:
                            retries: 10
                            statuses: BAD_GATEWAY
                            methods: GET
                            backoff:
                                firstBackoff: 10ms
                                maxBackoff: 100ms
                                factor: 2
                                basedOnPreviousValue: false

                                

eureka:
    client:
        fetch-register: true
        register-with-eureka: true
        defaultZone: http://localhost:8761/eureka
    instance:
        preferIpAddress: true
    
server:
    port: 8090
    
management:
  endpoint:
    gateway:
      enabled: true
    circuitbreakers:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
