spring:
    application:
        name: gateway
    zipkin:
        enabled: true
        base-url: http://localhost:9411
        sender.type: web
        locator:
            discovery:
                enabled: true
    sleuth:
        enabled: true
        sampler:
            probability: 1.0
    cloud:
        loadbalancer:
            ribbon:
                enabled: false
        gateway:
#            discovery:
 #               locator:
  #                  enabled: true
   #                 lower-case-service-id: true
            default-filters:
                - name: Retry
                  args:
                    retries: 3
                    methods: GET
                    statuses: BAD_GATEWAY
                    backoff:
                      firstBackoff: 50ms
                      maxBackoff: 500ms
                      factor: 2
                      basedOnPreiousValue: false
                
            routes:
                - id: product-route
                  uri: lb://PRODUCT/
                  predicates:
                    - Path=/product/**
                  filters:
                    - name: CircuitBreaker
                      args:
                        name: product_circuit_breaker
                        registerHealthIndicator: true
                        failureRateThreshold: 50
                        slidingWindowSize: 20
                        minimumNumberOfCalls: 20
                        waitDurationInOpenState: 10s
                        permmitedNumberOfCallsInHalfOpenState: 5
                - id: review-route
                  uri: lb://REVIEW/
                  predicates: 
                    - Path=/review/**
                  filters:
                    - name: CircuitBreaker
                      args:
                        name: review_circuit_breaker
                        registerHealthIndicator: true
                        failureRateThreshold: 50
                        slidingWindowSize: 20
                        minimumNumberOfCalls: 20
                        waitDurationInOpenState: 10s
                        permmitedNumberOfCallsInHalfOpenState: 5
                        
                - id: sales-route
                  uri: lb://SALES/
                  predicates: 
                    - Path=/order/**
                  filters:
                    - name: CircuitBreaker
                      args:
                        name: sales_circuit_breaker
                        registerHealthIndicator: true
                        failureRateThreshold: 50
                        slidingWindowSize: 20
                        minimumNumberOfCalls: 20
                        waitDurationInOpenState: 10s
                        permmitedNumberOfCallsInHalfOpenState: 5
                  

                                

eureka:
    client:
        fetch-register: true
        register-with-eureka: true
        defaultZone: http://localhost:8761/eureka
    instance:
        preferIpAddress: true
    
server:
    port: 8090
    
management:
  endpoint:
    gateway:
      enabled: true
    circuitbreakers:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
