spring:
    application:
        name: gateway
    cloud:
        loadbalancer:
            ribbon:
                enabled: false
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
                - id: product
                  uri: lb://PRODUCT
                  predicates:
                    - Path=/product/**
                - id: review
                  uri: lb://REVIEW
                  predicates: 
                    - Path=/review/**
                - id: sales
                  uri: lb://SALES
                  predicates: 
                    - Path=/order/**
                  

eureka:
    client:
        fetch-register: true
        register-with-eureka: true
        defaultZone: http://localhost:8761/eureka
    instance:
        preferIpAddress: true
    
server:
    port: 8090
    
management:
    endpoints:
        web:
            exposure:
                include: "*"
