spring:
    application:
        name: lb
    cloud:
        loadbalancer:
            ribbon:
                enabled: false

eureka:
    client:
        fetch-register: true
        register-with-eureka: true
        defaultZone: http://localhost:8761/eureka
    instance:
        preferIpAddress: true

server:
    port: 9000
