spring:
    application:
        name: product
    datasource:
        username: postgres
        password: postgres
        url: jdbc:postgresql://localhost:5432/product-back
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create
    cloud:
        loadbalancer:
            ribbon:
                enabled: false
                listOfServers: http://localhost:8080,http://localhost:8082
                ServerListRefreshInterval: 2000
eureka:
    client:
        fetch-register: true
        register-with-eureka: true
        defaultZone: http://localhost:8761/eureka
    instance:
        preferIpAddress: true
    
server:
    port: 8080

