spring:
    application:
        name: review
    datasource:
        username: postgres
        password: postgres
        url: jdbc:postgresql://localhost:5432/review-back
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create
    cloud:
        loadbalancer:
            ribbon:
                enabled: false
        

resilience4j.circuitbreaker:
    instances:
        servicebeta:
            registerHealthIndicator: true
            ringBufferSizeInClosedState: 5
            ringBufferSizeInHalfOpenState: 3
            waitDurationInOpenState: 10s
            failureRateThreshold: 5
            recordExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.io.IOException
                - java.lang.IllegalStateException
                - java.util.concurrent.TimeoutException
                - org.springframework.web.client.ResourceAccessException
                - java.lang.RuntimeException

resilience4j.thread-pool-bulkhead:
    instances:
        bulkheadservicebeta:
            maxThreadPoolSize: 1
            coreThreadPoolSize: 1
            queueCapacity: 1

resilience4j.retry:
    instances:
        retryservicebeta:
            maxRetryAttempts: 5
            waitDuration: 10000
            retry-exceptions:
                - java.util.concurrent.TimeoutException
                - java.net.ConnectException

eureka:
    client:
        fetch-register: true
        register-with-eureka: true
        defaultZone: http://localhost:8761/eureka
    instance:
        preferIpAddress: true

management:
    health:
        circuitbreakers:
            enabled: true
    endpoints:
        web:
            exposure:
                include: health
    endpoint:
        health:
            show-details: always

server:
    port: 8081
