spring:
    application:
        name: sales
    datasource:
        username: postgres
        password: postgres
        url: jdbc:postgresql://localhost:5432/sales-back
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create
    cloud:
        loadbalancer:
            ribbon:
                enabled: false

eureka:
    client:
        fetch-register: true
        register-with-eureka: true
        defaultZone: http://localhost:8761/eureka
    instance:
        preferIpAddress: true
    
server:
    port: 8085
