oi: teste

spring:
    application:
        name: product
    #zipkin:
        #enabled: true
        #base-url: http://localhost:9411
        #locator:
            #discovery:
                #enabled: true
    #sleuth:
        #enabled: true
        #sampler:
            #probability: 1.0
    datasource:
        username: postgres
        password: postgres
        #url: jdbc:postgresql://localhost:5432/product-back
        url: jdbc:h2:mem:testdb
    jpa:
        #properties:
            #hibernate:
                #dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create
        database-platform: org.hibernate.dialect.H2Dialect
    cloud:
        loadbalancer:
            ribbon:
                enabled: false
    cache:
        type: redis
    data:
        redis:
            #host: 192.168.56.1
            port: 6379
            timeout: 2000
            #password: admin



resilience4j.circuitbreaker:
    instances:
        checkProductBreaker:
            registerHealthIndicator: true
            ringBufferSizeInClosedState: 5
            ringBufferSizeInHalfOpenState: 3
            waitDurationInOpenState: 10s
            failureRateThreashold: 5
            recordExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.io.IOException
                - java.lang.IllegalStateException
                - java.util.concurrent.TimeoutException
                - org.springframework.web.client.ResourceAccessException
                - java.lang.RuntimeException

resilience4j.bulkhead:
    instances:
        checkProductBulk:
            maxWaitDuration: 2ms
            maxConcurrentCalls: 20

resilience4j.retry:
    instances:
        retryservicebeta:
            maxRetryAttempts: 5
            waitDuration: 1000

eureka:
    client:
        fetch-register: true
        register-with-eureka: true
        defaultZone: http://localhost:8761/eureka
    instance:
        preferIpAddress: true
        lease-renewal-interval-in-seconds: 2
        lease-expiration-duration-in-seconds: 5
    

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    circuitbreakers:
      enabled: true
    health:
      show-details: ALWAYS
  health:
    circuitbreakers:
      enabled: true

