spring:
    application:
        name: gateway
    # zipkin:
    #     enabled: true
    #     base-url: http://localhost:9411
    #     service.name: gateway
    #     sender.type: web
    #     locator:
    #         discovery:
    #             enabled: true
    # sleuth:
    #     enabled: true
    #     sampler:
    #         probability: 1
    cloud:
        loadbalancer:
            ribbon:
                enabled: false
        gateway:
          #  discovery:
          #      locator:
          #          enabled: true
          #          lowerCaseServiceId: true
            httpclient:
              connect-timeout: 2000
              response-timeout: 7s
            default-filters:
                - name: Retry
                  args:
                    retries: 3
                    methods: GET
                    statuses: BAD_GATEWAY
                    backoff:
                      firstBackoff: 50ms
                      maxBackoff: 500ms
                      factor: 2
                      basedOnPreiousValue: false
                
            routes:
                - id: product-route
                  uri: lb://PRODUCT/
                  predicates:
                    - Path=/product/**
                  # filters:
                  #   - name: CircuitBreaker
                  #     args:
                  #       name: product_circuit_breaker
                  #       registerHealthIndicator: true
                  #       failureRateThreshold: 50
                  #       slidingWindowSize: 20
                  #       minimumNumberOfCalls: 20
                  #       waitDurationInOpenState: 10s
                  #       permmitedNumberOfCallsInHalfOpenState: 5
                - id: review-route
                  uri: lb://REVIEW/
                  predicates: 
                    - Path=/review/**
                  # filters:
                  #   - name: CircuitBreaker
                  #     args:
                  #       name: review_circuit_breaker
                  #       registerHealthIndicator: true
                  #       failureRateThreshold: 50
                  #       slidingWindowSize: 20
                  #       minimumNumberOfCalls: 20
                  #       waitDurationInOpenState: 10s
                  #       permmitedNumberOfCallsInHalfOpenState: 5
                        
                - id: sales-route
                  uri: lb://SALES/
                  predicates: 
                    - Path=/order/**
                  # filters:
                  #   - name: CircuitBreaker
                  #     args:
                  #       name: sales_circuit_breaker
                  #       registerHealthIndicator: true
                  #       failureRateThreshold: 50
                  #       slidingWindowSize: 20
                  #       minimumNumberOfCalls: 20
                  #       waitDurationInOpenState: 10s
                  #       permmitedNumberOfCallsInHalfOpenState: 5
                - id: rproduct-route
                  uri: lb://REACTIVEPRODUCT/
                  predicates:
                    - Path=/reactive/product/**

                - id: rreview-route
                  uri: lb://REACTIVEREVIEW/
                  predicates:
                    - Path=/reactive/product-review/**

                - id: rsales-route
                  uri: lb://REACTIVESALES/
                  predicates:
                    - Path=/reactive/order/**
                                             

eureka:
    client:
        fetch-register: true
        register-with-eureka: true
        serviceUrl:
          defaultZone: http://localhost:8761/eureka
    instance:
        preferIpAddress: true
        lease-renewal-interval-in-seconds: 2
        lease-expiration-duration-in-seconds: 5
    
    
management:
  endpoint:
    gateway:
      enabled: true
    circuitbreakers:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
