spring:
    application:
        name: function
    zipkin:
        enabled: true
        base-url: http://localhost:9411
        locator:
            discovery:
                enabled: true
    sleuth:
        enabled: true
        sampler:
            probability: 1.0
        

eureka:
    client:
        fetch-register: true
        register-with-eureka: true
        defaultZone: http://localhost:8761/eureka
    instance:
        preferIpAddress: true
        lease-renewal-interval-in-seconds: 2
        lease-expiration-duration-in-seconds: 5
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    circuitbreakers:
      enabled: true
    health:
      show-details: ALWAYS   

server:
    port: 8020
