spring:
    application:
        name: eureka
    zipkin:
        enabled: true
        base-url: http://localhost:9411
        locator:
            discovery:
                enabled: true
    sleuth:
        enabled: true
        sampler:
            probability: 1.0
    cloud:
        loadbalancer:
            ribbon:
                enabled: false

eureka:
    client:
        fetch-register: false
        register-with-eureka: false
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    server:
        expected-client-renewal-interval-seconds: 2

